# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/kmfileserver .

    - name: SSH and run script
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          sudo systemctl stop kmfileserver

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        source: "bin/kmfileserver"
        target: "/usr/local/bin/kmfileserver"

    - name: SSH and run script
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          sudo chmod +x /usr/local/bin/kmfileserver
          sudo systemctl restart kmfileserver.service
